# Generated by Django 2.0.2 on 2018-02-10 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(to='map.Tag'),
        ),
        migrations.AddField(
            model_name='edge',
            name='node_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='map.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='node_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='map.Node'),
        ),
    ]
