# Generated by Django 2.0.2 on 2018-02-12 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(default='name', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='node',
            name='map',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='map.Map'),
            preserve_default=False,
        ),
    ]
