# Generated by Django 2.0.2 on 2018-02-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20180212_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='fill',
            field=models.CharField(default='red', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='r',
            field=models.IntegerField(default=5),
        ),
    ]
