# Generated by Django 2.0.2 on 2018-02-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20180212_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='stroke',
            field=models.CharField(default='black', max_length=20),
            preserve_default=False,
        ),
    ]
