# Generated by Django 2.0.2 on 2018-02-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_edge_stroke'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='edge',
            name='stroke',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
